 export const listData = [
  {
    id: 1,
    title: "Modern 2BHK apartment in Dhanmondi",
    img: "house1.png",
    bedroom: 2,
    bathroom: 2,
    price: 12500000,
    address: "House 12, Road 5, Dhanmondi, Dhaka 1205",
    latitude: 23.7465,
    longitude: 90.3760,
  },
  {
    id: 2,
    title: "Spacious flat near Chittagong city center",
    img: "house2.png",
    bedroom: 3,
    bathroom: 3,
    price: 9500000,
    address: "GEC Circle, Chittagong",
    latitude: 22.3569,
    longitude: 91.7832,
  },
  {
    id: 3,
    title: "Luxury condo in Gulshan",
    img: "house3.png",
    bedroom: 3,
    bathroom: 3,
    price: 18000000,
    address: "Road 35, Gulshan-2, Dhaka",
    latitude: 23.7925,
    longitude: 90.4078,
  },
  {
    id: 4,
    title: "Stylish 2BHK flat in Mirpur DOHS",
    img: "house4.png",
    bedroom: 2,
    bathroom: 2,
    price: 6900000,
    address: "Road 8, Mirpur DOHS, Dhaka",
    latitude: 23.8169,
    longitude: 90.3654,
  },
  {
    id: 5,
    title: "Family apartment in Uttara Sector 11",
    img: "house5.png",
    bedroom: 3,
    bathroom: 3,
    price: 7900000,
    address: "Road 15, Sector 11, Uttara, Dhaka",
    latitude: 23.8761,
    longitude: 90.3796,
  },
  {
    id: 6,
    title: "Lakeview apartment in Baridhara DOHS",
    img: "house6.png",
    bedroom: 3,
    bathroom: 3,
    price: 16500000,
    address: "Block C, Baridhara DOHS, Dhaka",
    latitude: 23.8106,
    longitude: 90.4250,
  },
  {
    id: 7,
    title: "Affordable 2BHK flat in Khulna city",
    img: "house7.png",
    bedroom: 2,
    bathroom: 2,
    price: 5500000,
    address: "Sonadanga Residential Area, Khulna",
    latitude: 22.8456,
    longitude: 89.5403,
  },
  {
    id: 8,
    title: "Corporate-ready office apartment in Motijheel",
    img: "house8.png",
    bedroom: 2,
    bathroom: 2,
    price: 22000000,
    address: "Motijheel Commercial Area, Dhaka",
    latitude: 23.7324,
    longitude: 90.4160,
  },
  {
    id: 9,
    title: "Elegant duplex in Bashundhara R/A",
    img: "house9.png",
    bedroom: 4,
    bathroom: 4,
    price: 25000000,
    address: "Block D, Bashundhara Residential Area, Dhaka",
    latitude: 23.8151,
    longitude: 90.4287,
  },
  {
    id: 10,
    title: "Newly-built house in Sylhet town",
    img: "house10.png",
    bedroom: 3,
    bathroom: 3,
    price: 8900000,
    address: "Zindabazar, Sylhet",
    latitude: 24.8949,
    longitude: 91.8687,
  },
];


export const singlePostData = {
  id: 1,
  title: "Modern 2BHK apartment in Dhanmondi",
  price: 12500000,
  images: [
    "bedroom1.png",
    "bed2.png",
    "kitchen1.png",
    "bathromm1.png",
  ],
  bedroom: 2,
  bathroom: 2,
  size: "1200 sq ft",
  latitude: 23.7465,
  longitude: 90.3760,
  city: "Dhaka",
  address: "House 12, Road 5, Dhanmondi, Dhaka 1205",
  school: "250m away",
  bus: "100m away",
  restaurant: "200m away",
  description: "A beautifully designed 2BHK apartment located in the heart of Dhanmondi, ideal for families and professionals. With easy access to all amenities and a modern design, this property is perfect for those looking for comfort and convenience. It features spacious rooms, a well-equipped kitchen, and a balcony with a scenic view.",
};


export const userData={
  id:1,
  name:"Rahim khan",
  img:"user1.jpg",
};

